force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case’s Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Received Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ClosedCases__c.field-meta.xml
<CustomField>
    <fullName>ClosedCases__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closed Cases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseService.cls
public with sharing class CaseService {
    public static void updateCaseSuccessMessage(List<Case> cases, Map<Id, Case> oldCases) {
        Map<Id, Country__c> countries = new Map<Id, Country__c>(getClosedCaseCountries(cases, oldCases));

        for (Case c : cases) {
            if (c.Country__c == null) {
                continue;
            }

            c.SuccessMessage__c = countries.get(c.Country__c).SuccessMessage__c;
        }
    }

    public static void updateClosedCasesCount(List<Case> cases, Map<Id, Case> oldCases) {
        List<Country__c> countries = getClosedCaseCountries(cases, oldCases);

        for (Country__c country: countries) {
            country.ClosedCases__c = country.Cases__r.size();
        }

        update countries;
    }

    private static List<Country__c> getClosedCaseCountries(List<Case> cases, Map<Id, Case> oldCases) {
        Set<Id> countryIds = new Set<Id>();

        for (Case c : cases) {
            if (c.Status == 'Closed' && oldCases.get(c.Id).Status != 'Closed') {
                countryIds.add(c.Country__c);
            }

        }

        return CountrySelector.getByIds(countryIds);
    }
}