force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case’s Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Received Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ClosedCases__c.field-meta.xml
<CustomField>
    <fullName>ClosedCases__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closed Cases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountrySelector.cls
public with sharing class CountrySelector {

    public static List<Country__c> getByIds(Set<Id> ids) {
        return [
                SELECT Id, SuccessMessage__c, ClosedCases__c, (
                        SELECT Id
                        FROM Cases__r
                        WHERE Status = 'Closed'
                )
                FROM Country__c
                WHERE Id IN :ids
        ];
    }
}