force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case’s Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Received Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ClosedCases__c.field-meta.xml
<CustomField>
    <fullName>ClosedCases__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closed Cases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/SuccessMessage__c.field-meta.xml
<CustomField>
    <fullName>SuccessMessage__c</fullName>
    <label>Success Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
/**
 * Created by Yulisha on 7/29/2022.
 */

@IsTest class CaseTriggerTest {

    @IsTest static void testUpdateCaseSuccessMessage() {
        // GIVEN
        Country__c country = new Country__c(Name = 'Ukraine', SuccessMessage__c = 'Test');
        insert country;
        Case aCase = new Case(Country__c = country.Id, Status = 'Pending');
        insert aCase;

        // WHEN
        aCase.Status = 'Closed';
        update aCase;

        // THEN
        System.assertEquals(country.SuccessMessage__c, [SELECT SuccessMessage__c FROM Case].SuccessMessage__c);
    }

    @IsTest static void testClosedCaseCountOnCountry() {
        // GIVEN
        Country__c country = new Country__c(Name = 'Ukraine', ClosedCases__c = 0);
        insert country;
        Case aCase = new Case(Country__c = country.Id, Status = 'Pending');
        insert aCase;

        // WHEN
        aCase.Status = 'Closed';
        update aCase;

        // THEN
        System.assertEquals(1, [SELECT ClosedCases__c FROM Country__c].ClosedCases__c);
    }
}