force-app/main/default/objects/Flight_Info__c/Flight_Info__c.object-meta.xml
<CustomObject>
    <label>Flight Info</label>
    <nameField>
        <displayFormat>FI-{00000}</displayFormat>
        <label>Flight Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Info__c/fields/Date_time_of_Flight__c.field-meta.xml
<CustomField>
    <fullName>Date_time_of_Flight__c</fullName>
    <label>Date time of Flight</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight_Info__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight_Info__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight_Info__c.field-meta.xml
<CustomField>
    <fullName>Flight_Info__c</fullName>
    <label>Flight Info</label>
    <referenceTo>Flight_Info__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TicketController.cls
public with sharing class TicketController {
    @AuraEnabled
    public static void createTicket(Id recordId, String destination, String departure, String type, Datetime flightDate) {
        List<Flight_Info__c> flightInfo = [
                SELECT Id
                FROM Flight_Info__c
                WHERE Departure__c = :departure AND
                Destination__c = :destination AND
                Date_time_of_Flight__c >= :flightDate AND
                Date_time_of_Arrival__c <= :flightDate
        ];

        if (flightInfo.isEmpty()) {
            throw new AuraHandledException('Not Flight Info Found');
        }

        try {
            Id recordTypeId = SObjectType.Ticket__c.getRecordTypeInfosByDeveloperName().get(type).recordTypeId;
            insert new Ticket__c(Customer__c = recordId, Flight_Info__c = flightInfo[0].Id, RecordTypeId = recordTypeId);
        }
        catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}